name: CI

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  build-test-ubuntu-stack:
    runs-on: ubuntu-latest
    name: Ubuntu / Stack
    steps:
    - uses: actions/checkout@v2

    # relative paths are relative to the project directory
    - name: Cache Stack build artifacts (user + project)
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          .stack-work
        # best effort for cache: tie it to Stack resolver and package config
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack

    - name: Install project dependencies
      run: stack --no-terminal test --only-dependencies

    - name: Build and run tests
      run: stack --no-terminal haddock --test --no-haddock-deps

  build-test-ubuntu-cabal:
    runs-on: ubuntu-latest
    name: Ubuntu / GHC ${{ matrix.ghc }}, Cabal ${{ matrix.cabal }}
    strategy:
      matrix:
        cabal: ["3.2"] # latest as of 2021-02-23
        ghc:
#        - "8.6"
#        - "8.8"
        - "8.10"
#        - latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell build environment
      id: setup-haskell-build-env
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Freeze Cabal plan
      run: cabal freeze --enable-tests --enable-benchmarks

    - name: Cache Cabal build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.setup-haskell-build-env.outputs.cabal-store }}
          dist-newstyle
        key: fresh1-${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          fresh1-${{ runner.os }}-cabal-${{ matrix.ghc }}

    - name: TODO dist folder before
      run: du -hcd1 dist-newstyle

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks

    - name: Test
      run: cabal test --test-show-details=streaming
      env:
        HSPEC_OPTIONS: --color

    - name: TODO dist folder after
      run: du -hcd1 dist-newstyle
